#ifndef CMFEM_COMMON_H
#define CMFEM_COMMON_H

#include <stddef.h>

#if defined(__cplusplus)
#define CMFEM_BEGIN_EXTERN_C extern "C" {
#define CMFEM_END_EXTERN_C }
#else
#define CMFEM_BEGIN_EXTERN_C
#define CMFEM_END_EXTERN_C
#endif

typedef struct CMFEM_ArrayInt CMFEM_ArrayInt;
typedef struct CMFEM_Mesh CMFEM_Mesh;
typedef struct CMFEM_H1FeCollection CMFEM_H1FeCollection;
typedef struct CMFEM_NdFeCollection CMFEM_NdFeCollection;
typedef struct CMFEM_NdR1dFeCollection CMFEM_NdR1dFeCollection;
typedef struct CMFEM_NdR2dFeCollection CMFEM_NdR2dFeCollection;
typedef struct CMFEM_RtFeCollection CMFEM_RtFeCollection;
typedef struct CMFEM_RtTraceFeCollection CMFEM_RtTraceFeCollection;
typedef struct CMFEM_DgFeCollection CMFEM_DgFeCollection;
typedef struct CMFEM_DgInterfaceFeCollection CMFEM_DgInterfaceFeCollection;
typedef struct CMFEM_FiniteElementSpace CMFEM_FiniteElementSpace;
typedef struct CMFEM_GridFunction CMFEM_GridFunction;
typedef struct CMFEM_GridFunctionCoefficient CMFEM_GridFunctionCoefficient;
typedef struct CMFEM_LinearForm CMFEM_LinearForm;
typedef struct CMFEM_BilinearForm CMFEM_BilinearForm;
typedef struct CMFEM_MixedBilinearForm CMFEM_MixedBilinearForm;
typedef struct CMFEM_DiscreteLinearOperator CMFEM_DiscreteLinearOperator;
typedef struct CMFEM_BlockOperator CMFEM_BlockOperator;
typedef struct CMFEM_BlockDiagonalPreconditioner
   CMFEM_BlockDiagonalPreconditioner;
typedef struct CMFEM_RAPOperator CMFEM_RAPOperator;
typedef struct CMFEM_SparseMatrix CMFEM_SparseMatrix;
typedef struct CMFEM_Vector CMFEM_Vector;
typedef struct CMFEM_CGSolver CMFEM_CGSolver;
typedef struct CMFEM_GSSmoother CMFEM_GSSmoother;
typedef struct CMFEM_DSmoother CMFEM_DSmoother;
typedef struct CMFEM_SchurConstrainedSolver CMFEM_SchurConstrainedSolver;
typedef struct CMFEM_Device CMFEM_Device;
typedef struct CMFEM_SIAVSolver CMFEM_SIAVSolver;
typedef struct CMFEM_TimeDependentOperator CMFEM_TimeDependentOperator;
typedef struct CMFEM_ODESolver CMFEM_ODESolver;
typedef struct CMFEM_SecondOrderTimeDependentOperator
   CMFEM_SecondOrderTimeDependentOperator;
typedef struct CMFEM_SecondOrderODESolver CMFEM_SecondOrderODESolver;
typedef struct CMFEM_OperatorPtr CMFEM_OperatorPtr;
typedef struct CMFEM_OperatorJacobiSmoother CMFEM_OperatorJacobiSmoother;
typedef struct CMFEM_ConstantCoefficient CMFEM_ConstantCoefficient;
typedef struct CMFEM_FunctionCoefficient CMFEM_FunctionCoefficient;
typedef struct CMFEM_MatrixFunctionCoefficient CMFEM_MatrixFunctionCoefficient;
typedef struct CMFEM_VectorConstantCoefficient CMFEM_VectorConstantCoefficient;
typedef struct CMFEM_PWConstCoefficient CMFEM_PWConstCoefficient;
typedef struct CMFEM_VectorArrayCoefficient CMFEM_VectorArrayCoefficient;
typedef struct CMFEM_VectorFunctionCoefficient CMFEM_VectorFunctionCoefficient;
typedef struct CMFEM_CoefficientRefiner CMFEM_CoefficientRefiner;
typedef struct CMFEM_DiffusionIntegrator CMFEM_DiffusionIntegrator;
typedef struct CMFEM_ElasticityIntegrator CMFEM_ElasticityIntegrator;
typedef struct CMFEM_ZienkiewiczZhuEstimator CMFEM_ZienkiewiczZhuEstimator;
typedef struct CMFEM_LSZienkiewiczZhuEstimator CMFEM_LSZienkiewiczZhuEstimator;
typedef struct CMFEM_KellyErrorEstimator CMFEM_KellyErrorEstimator;
typedef struct CMFEM_ThresholdRefiner CMFEM_ThresholdRefiner;
typedef struct CMFEM_ThresholdDerefiner CMFEM_ThresholdDerefiner;
typedef struct CMFEM_L2FeCollection CMFEM_L2FeCollection;
typedef struct CMFEM_VisItDataCollection CMFEM_VisItDataCollection;

#define CMFEM_STORAGE(Name, Size) struct CMFEM_##Name { char data[Size]; }

#endif
