# Copyright (c) 2010-2025, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: "Tests"

on:
  push:
    branches:
      - master
      - next
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.16.0

jobs:
  zig-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: debug-static
            optimize: Debug
            extra_args: ""
            build_targets: true
          - name: release-static
            optimize: ReleaseSafe
            extra_args: ""
            build_targets: true
          - name: release-shared
            optimize: ReleaseSafe
            extra_args: "-Dshared=true"
            build_targets: false
          - name: release-single-precision
            optimize: ReleaseSafe
            extra_args: "-Dprecision=single"
            build_targets: false

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Check build script formatting
        run: zig fmt --check build.zig

      - name: Build
        run: zig build -Doptimize=${{ matrix.optimize }} ${{ matrix.extra_args }} --summary all

      - name: Build Examples
        if: ${{ matrix.build_targets }}
        run: zig build examples -Doptimize=${{ matrix.optimize }} ${{ matrix.extra_args }} --summary all

      - name: Build Miniapps
        if: ${{ matrix.build_targets }}
        run: zig build miniapps -Doptimize=${{ matrix.optimize }} ${{ matrix.extra_args }} --summary all

      - name: Build And Run Tests
        if: ${{ matrix.build_targets }}
        run: zig build test -Doptimize=${{ matrix.optimize }} ${{ matrix.extra_args }} --summary all
