#!/bin/bash

# Copyright (c) 2010-2025, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

# Print usage information
case $1 in
   -h|-help)
      cat <<EOF

   $0 [-h|-help] {mfem_dir}

   where: {mfem_dir}  is the MFEM source directory [default value: ../..]
          -h|-help    prints this usage information and exits

   This script runs documentation-related tests in mfem_dir. It checks in
   particular the Doxygen formatting used in the source comments.

   Example usage: $0 ../..

EOF
      exit
      ;;
esac

# Setup
cur_dir=$(pwd)
mfem_dir=$1
if [ "$mfem_dir" = "" ]; then
    mfem_dir="../.."
fi
shift
mfem_dir=$(cd "$mfem_dir" && pwd)
cd "$mfem_dir"

# Test the build of the Doxygen documentation
cd doc
rm -rf CodeDocumentation CodeDocumentation.conf CodeDocumentation.html
rm -f undoc.log warnings.log
sed -e "s%@MFEM_SOURCE_DIR@%$mfem_dir%g" CodeDocumentation.conf.in \
  > CodeDocumentation.conf
doxygen CodeDocumentation.conf
printf '%s\n' \
  '<meta http-equiv="REFRESH" content="0;URL=CodeDocumentation/html/index.html">' \
  > CodeDocumentation.html
cat warnings.log 1>&2
{ cat CodeDocumentation.conf; \
  printf 'GENERATE_HTML=NO\nEXTRACT_ALL=NO\nWARN_LOGFILE=undoc.log\nQUIET=YES\n'; \
} | doxygen - > /dev/null 2>&1

# Return to the original directory
cd $cur_dir

# Tell users what to do if the script fails
test_name="$(basename "$0")"
if [ -s "$test_name.err" ]; then
    cat >  $test_name.msg <<EOF

To correct this error, make sure that the Doxygen comments in the code use
correct syntax.

See the Doxygen documentation for specific syntax (e.g. @a, @brief, etc.),
and the 'CodeDocumentation.conf.in' file in the 'doc/' directory for
additional details.

Please contact a member of the MFEM team if you have questions.

EOF
fi
